server {
    # Cloud Run espera que la aplicación escuche en el puerto 8080
    listen 8080;
    server_name localhost;

    location / {
        # Directorio de los archivos estáticos
        root /usr/share/nginx/html;
        index index.html index.htm;
        
        # Enrutamiento tipo SPA
        try_files $uri $uri/ /index.html;
    }

    # Manejo de errores
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}